apiVersion: v1
kind: Service
metadata:
 name: theia-next
spec:
 type: LoadBalancer
 ports:
 - port: 3000
   nodePort: 32400
 selector:
   app: theia-next
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia-next
  name: theia-next
spec:
  selector:
    matchLabels:
      app: theia-next
  replicas: 1
  template:
    metadata:
      labels:
        app: theia-next
    spec:
      containers:
      - image: theiaide/theia-full
        imagePullPolicy: IfNotPresent
        name: theia-next
        ports:
        - containerPort: 3000
        # Volumes im Container - wie maven
        volumeMounts:
        - mountPath: "/home/project"
          subPath: src           
          name: "theia-storage"
      # Volumes in Host
      volumes:
      - name: theia-storage
        persistentVolumeClaim:
         claimName: data-claim          
